### ISSUE TITLE
When no %env is provided, should default to %*ENV

### ISSUE THREAD

**Issue by zerodogg** [CurtTilmes/perl6-native-exec#1]
raku doesn't sync %*ENV with the OS environment by default. It just does so upon i.e. run().

This doesn't work:

```raku
#!/usr/bin/env raku
use Native::Exec;
sub MAIN (Bool :$done)
{
    if $done
    {
        say %*ENV<TEST_ENV_VAR>;
    }
    else
    {
        %*ENV<TEST_ENV_VAR> = "Hello world";
        exec($*PROGRAM-NAME,'--done');
    }
}
```

I would expect this to output "Hello world". Instead it outputs "(Any)".

This works:

```raku
#!/usr/bin/env raku
use Native::Exec;
sub MAIN (Bool :$done)
{
    if $done
    {
        say %*ENV<TEST_ENV_VAR>;
    }
    else
    {
        %*ENV<TEST_ENV_VAR> = "Hello world";
        exec($*PROGRAM-NAME,'--done', |%*ENV);
    }
}
```

To fit in with expectations, Native::Exec should default to using %*ENV as the environment for the exec-ed process.

**Comment by CurtTilmes** [comment]
I like the way it works now.  I thought about adding an option to use the Raku ENV, but really it is easy enough to just pass it in if you want it.  I added some more docs to clarify the behavior and describe how to use the Raku ENV if you want it.
